const developers = [
 {name:'Vinicius', cv:'assets/curriculos/Vinicius-Moreira-Navarro-Venancio-Curriculo.pdf', role:'Desenvolvedor Web', formation:'Técnico em Desenvolvimento de Sistemas — Concluído', stack:'HTML • CSS • JavaScript', project:'Portal Institucional', photo:'Vinicius.jpeg', bio:'Atuação voltada à criação de interfaces modernas, responsivas e fáceis de usar.', skills:['HTML5','CSS3','JavaScript','Git'], projects:['Portal Institucional','Landing Page Responsiva','Página de Serviços']},
 {name:'Dayane', cv:'assets/curriculos/Dayane-Lopes-Silva-Curriculo.pdf', role:'Desenvolvedora Front-end', formation:'Técnico em Desenvolvimento de Sistemas — Concluído', stack:'HTML • CSS • JavaScript • UI/UX', project:'Interface Digital', photo:'Dayane.jpeg', bio:'Foco em experiência do usuário, organização visual e desenvolvimento de interfaces web.', skills:['HTML5','CSS3','JavaScript','UI/UX'], projects:['Dashboard Web','Landing Page','Protótipo de Interface']},
 {name:'Leleo', role:'Desenvolvedor de Sistemas', formation:'Técnico em Desenvolvimento de Sistemas — Concluído', stack:'Python • POO • Sistemas', project:'Sistema de Gestão', photo:'Leleo.jpeg', bio:'Interesse em lógica de programação, orientação a objetos e desenvolvimento de sistemas.', skills:['Python','POO','Lógica','Git'], projects:['Sistema de Gestão','Cadastro de Usuários','Sistema de Relatórios']},
 {name:'Jullya', cv:'assets/curriculos/Jullya-Leite-da-Silva-Flores-Curriculo.pdf', role:'Desenvolvedora Web', formation:'Técnico em Desenvolvimento de Sistemas — Concluído', stack:'HTML • CSS • JavaScript', project:'Portfólio Criativo', photo:'Jullya.jpeg', bio:'Desenvolvimento de páginas web com atenção à apresentação, responsividade e usabilidade.', skills:['HTML5','CSS3','JavaScript','Design'], projects:['Portfólio Criativo','Galeria Responsiva','Página Pessoal']},
 {name:'Carlos', role:'Desenvolvedor Full Stack', formation:'Técnico em Desenvolvimento de Sistemas — Concluído', stack:'JavaScript • Node.js • Web', project:'API de Serviços', photo:'Carlos.jpeg', bio:'Interesse em aplicações completas, APIs e integração entre front-end e back-end.', skills:['JavaScript','Node.js','APIs','Git'], projects:['API de Serviços','Sistema Web','Integração REST']},
 {name:'Enrique', cv:'assets/curriculos/Enrique-Candia-Martins-Curriculo.pdf', role:'Desenvolvedor de Sistemas', formation:'Técnico em Desenvolvimento de Sistemas — Concluído', stack:'Python • Banco de Dados • Web', project:'Sistema Acadêmico', photo:'Enrique.jpeg', bio:'Foco em sistemas, organização de dados e construção de soluções para processos acadêmicos.', skills:['Python','SQL','Flask','Git'], projects:['Sistema Acadêmico','Controle de Salas','Relatórios']},
 {name:'Freddy', role:'Desenvolvedor Web', formation:'Técnico em Desenvolvimento de Sistemas — Concluído', stack:'HTML • CSS • JavaScript • PHP', project:'Site Dinâmico', photo:'Freddy.jpeg', bio:'Atuação em desenvolvimento web e construção de páginas dinâmicas para diferentes necessidades.', skills:['HTML5','CSS3','JavaScript','PHP'], projects:['Site Dinâmico','Formulário PHP','Página Institucional']},
 {name:'Fabio', cv:'assets/curriculos/Fabio-Junior-Curriculo.pdf', role:'Desenvolvedor de Sistemas', formation:'Técnico em Desenvolvimento de Sistemas — Concluído', stack:'Python • POO • Banco de Dados', project:'Gestor de Dados', photo:'Fabio.jpeg', bio:'Interesse em programação estruturada, orientação a objetos e persistência de dados.', skills:['Python','POO','SQL','Git'], projects:['Gestor de Dados','Sistema de Cadastro','Controle de Estoque']},
 {name:'Mateus', cv:'assets/curriculos/Mateus-Leite-da-Silva-Curriculo.pdf', role:'Desenvolvedor de Sistemas', formation:'Técnico em Desenvolvimento de Sistemas — Concluído', stack:'Python • HTML • CSS • Banco de Dados', project:'Sistema de Gestão Escolar', photo:'Mateus.jpeg', bio:'Desenvolvedor com foco em Python, web e construção de projetos práticos.', skills:['Python','HTML','CSS','Banco de Dados','Flask'], projects:['Sistema de Gestão Escolar','Controle de Reservas','Site Desenvolvedores Corumbá']},
 {name:'Pedro', role:'Desenvolvedor Web', formation:'Técnico em Desenvolvimento de Sistemas — Concluído', stack:'HTML • CSS • JavaScript', project:'Web Experience', photo:'Pedro.jpeg', bio:'Criação de experiências web responsivas e componentes visuais para projetos digitais.', skills:['HTML5','CSS3','JavaScript','Responsividade'], projects:['Web Experience','Página de Produto','Galeria Interativa']},
 {name:'Felipe', role:'Desenvolvedor Full Stack', formation:'Técnico em Desenvolvimento de Sistemas — Concluído', stack:'JavaScript • Python • Web', project:'Aplicação Integrada', photo:'Felipe.jpeg', bio:'Interesse em desenvolvimento full stack e integração de diferentes tecnologias em uma mesma solução.', skills:['JavaScript','Python','APIs','Banco de Dados'], projects:['Aplicação Integrada','API REST','Sistema Web']},
 {name:'Ana', role:'Desenvolvedor de Software', formation:'Técnico em Desenvolvimento de Sistemas — Concluído', stack:'Python • IA • Automação', project:'Automação Inteligente', photo:'dev12.svg', bio:'Perfil demonstrativo reservado para o décimo segundo integrante da equipe.', skills:['Python','Automação','IA','Lógica'], projects:['Automação Inteligente','Assistente Virtual','Processamento de Dados']}
];

function shuffleDevelopers(list){const shuffled=[...list];for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]];}return shuffled;}
function getRandomDeveloperOrder(){const current=shuffleDevelopers(developers);try{const previous=JSON.parse(sessionStorage.getItem('devOrder')||'null');if(previous&&previous.length===current.length&&current.length>1&&current[0].name===previous[0]){[current[0],current[1]]=[current[1],current[0]];}sessionStorage.setItem('devOrder',JSON.stringify(current.map(d=>d.name)));}catch(e){}return current;}
const developerPhotoPositions = {
  Vinicius: '50% 25%',
  Fabio: '50% 50%',
  Carlos: '50% 48%',
  Mateus: '50% 38%',
  Felipe: '50% 36%',
  Leleo: '50% 28%',
  Freddy: '50% 38%',
  Jullya: '50% 36%',
  Enrique: '50% 38%',
  Pedro: '50% 40%',
  Dayane: '50% 50%',
  'Desenvolvedor 12': '50% 50%'
};

function renderDevelopers(){const grid=document.getElementById('devGrid');if(!grid)return;const ordered=getRandomDeveloperOrder();grid.innerHTML=ordered.map(d=>{const i=developers.indexOf(d);return `<article class="dev-card reveal"><a class="dev-photo" href="portfolio.html?dev=${i}" aria-label="Abrir portfólio de ${d.name}"><img class="developer-image" style="object-position:${developerPhotoPositions[d.name] || '50% 50%'}" src="assets/desenvolvedores/${d.photo}" alt="Foto de ${d.name}" loading="lazy" onerror="this.parentElement.classList.add('no-image');this.style.display='none'"><span class="photo-overlay">VER PORTFÓLIO ↗</span></a><div class="dev-info"><h3>${d.name}</h3><p class="dev-role">${d.role}</p><p class="dev-stack">${d.stack}</p><p class="dev-project"><b>Projeto:</b> ${d.project}</p><p class="dev-formation"><b>Formação:</b> ${d.formation}</p><a class="cv-link" href="portfolio.html?dev=${i}">Currículo / Portfólio ↗</a></div></article>`;}).join('');observeReveals();}
function renderPortfolio(){const root=document.getElementById('portfolioContent');if(!root)return;const params=new URLSearchParams(location.search);let i=Number(params.get('dev'));if(!Number.isInteger(i)||i<0||i>=developers.length)i=0;const d=developers[i];document.title=`${d.name} | Portfólio`;root.innerHTML=`<section class="portfolio-hero"><div class="portfolio-photo"><img class="developer-image" style="object-position:${developerPhotoPositions[d.name] || '50% 50%'}" src="assets/desenvolvedores/${d.photo}" alt="Foto de ${d.name}"></div><div class="portfolio-intro"><span class="eyebrow">PORTFÓLIO INDIVIDUAL</span><h1>${d.name}</h1><h2>${d.role}</h2><p>${d.bio}</p><div class="portfolio-tags">${d.skills.map(s=>`<span>${s}</span>`).join('')}</div><div class="portfolio-actions"><a class="primary-action" href="index.html#contato">✉ Entrar em contato</a>${d.cv ? `<a class="secondary-action cv-download" href="${d.cv}" download>⬇ Baixar currículo</a>` : ""}<a class="secondary-action" href="index.html#equipe">← Equipe</a></div></div></section><section class="portfolio-body section"><div class="section-title left"><span>CURRÍCULO</span><h2>Perfil profissional</h2></div><div class="resume-grid"><article class="resume-card"><h3>Formação</h3><p>${d.formation}</p></article><article class="resume-card"><h3>Stack principal</h3><ul>${d.skills.map(s=>`<li>${s}</li>`).join('')}</ul></article><article class="resume-card resume-wide"><h3>Resumo profissional</h3><p>${d.bio} Esta página é demonstrativa e pode ser personalizada com experiência, certificados, links profissionais e informações de contato reais.</p></article></div><div class="section-title left project-title"><span>PROJETOS</span><h2>Projetos desenvolvidos</h2></div><div class="portfolio-projects">${d.projects.map((p,n)=>`<article class="portfolio-project"><span>${String(n+1).padStart(2,'0')}</span><h3>${p}</h3><p>Projeto demonstrativo que pode receber descrição, tecnologias utilizadas, imagens e link para publicação.</p><a href="index.html#contato">Solicitar detalhes →</a></article>`).join('')}</div></section>`;}
function observeReveals(){const els=document.querySelectorAll('.reveal:not(.seen)');if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('seen'));return;}const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('seen');io.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>io.observe(e));}
function initHero(){const slides=[...document.querySelectorAll('.hero-slide')],dots=[...document.querySelectorAll('.hero-dots button')];if(!slides.length)return;let index=0,timer;const show=n=>{index=(n+slides.length)%slides.length;slides.forEach((s,i)=>s.classList.toggle('active',i===index));dots.forEach((d,i)=>d.classList.toggle('active',i===index));};const restart=()=>{clearInterval(timer);timer=setInterval(()=>show(index+1),6000)};document.querySelector('.hero-btn.next')?.addEventListener('click',()=>{show(index+1);restart()});document.querySelector('.hero-btn.prev')?.addEventListener('click',()=>{show(index-1);restart()});dots.forEach((d,i)=>d.addEventListener('click',()=>{show(i);restart()}));restart();}
function initMenu(){const btn=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav-menu');if(!btn||!nav)return;btn.addEventListener('click',()=>{const open=nav.classList.toggle('open');btn.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
function initMatrix(){const canvas=document.getElementById('matrixCanvas');if(!canvas)return;const ctx=canvas.getContext('2d');const chars='01アイウエオカキクケコサシスセソタチツテトABCDEFGHIJKLMNOPQRSTUVWXYZ';let fontSize=15,columns,drops;function resize(){canvas.width=innerWidth;canvas.height=innerHeight;columns=Math.floor(canvas.width/fontSize);drops=Array(columns).fill(1).map(()=>Math.random()*-40);}resize();addEventListener('resize',resize);function draw(){ctx.fillStyle='rgba(3,8,12,0.09)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='rgba(44,255,120,0.32)';ctx.font=`${fontSize}px monospace`;for(let i=0;i<drops.length;i++){const text=chars[Math.floor(Math.random()*chars.length)];ctx.fillText(text,i*fontSize,drops[i]*fontSize);if(drops[i]*fontSize>canvas.height&&Math.random()>.975)drops[i]=0;drops[i]+=.65;}requestAnimationFrame(draw);}draw();}
renderDevelopers();renderPortfolio();initHero();initMenu();initMatrix();
